# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DirMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainui_dir(object):
    def setupUi(self, mainui_dir):
        mainui_dir.setObjectName("mainui_dir")
        mainui_dir.resize(705, 393)
        self.centralwidget = QtWidgets.QWidget(mainui_dir)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(120, 30, 361, 31))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 54, 12))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(500, 30, 75, 31))
        self.pushButton.setObjectName("pushButton")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(80, 120, 501, 211))
        self.textEdit_2.setObjectName("textEdit_2")
        self.btn_unpack = QtWidgets.QPushButton(self.centralwidget)
        self.btn_unpack.setGeometry(QtCore.QRect(80, 70, 501, 41))
        self.btn_unpack.setObjectName("btn_unpack")
        mainui_dir.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainui_dir)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 23))
        self.menubar.setObjectName("menubar")
        mainui_dir.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainui_dir)
        self.statusbar.setObjectName("statusbar")
        mainui_dir.setStatusBar(self.statusbar)

        self.retranslateUi(mainui_dir)
        QtCore.QMetaObject.connectSlotsByName(mainui_dir)

        # 初始化事件
        self.pushButton.clicked.connect(self.chooseDirectory)

    def retranslateUi(self, mainui_dir):
        _translate = QtCore.QCoreApplication.translate
        mainui_dir.setWindowTitle(_translate("mainui_dir", "mainui_dir"))
        self.label.setText(_translate("mainui_dir", "目录"))
        self.pushButton.setText(_translate("mainui_dir", "浏览"))
        self.btn_unpack.setText(_translate("mainui_dir", "unpack"))

    # 选择目录
    def chooseDirectory(self):
        try:
            directory = QtWidgets.QFileDialog.getExistingDirectory(None, "choose Directory", "./")
            if directory:
                self.textEdit.setText(directory)
                self.outputLog("path={}\n".format(self.textEdit.toPlainText()))
        except Exception as e:
            self.outputLog('{}\n'.format(e))

    # 输出日志
    def outputLog(self, text=None):
        cursor = self.textEdit_2.textCursor()
        cursor.movePosition(QtGui.QTextCursor.End)
        cursor.insertText(text)
        self.textEdit_2.setTextCursor(cursor)
        self.textEdit_2.ensureCursorVisible()